version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /Users/maximilianreihn/Documents/repos/zwift-python-noteboook/zwo_files/:/src/zwo_files/