version: "3"
services:
  web:
    build: .
    restart: always
    privileged: true
    ports:
      - "5000:80"
    volumes:
      #- /Users/maximilianreihn/Documents/repos/zwift-python-noteboook/zwo_files/:/src/zwo_files/
      - /volume1/generator/zwo_files/:/src/zwo_files/