version: "3"
services:
  web:
    environment:
      TZ: "Europe/Berlin"
    build: .
    restart: always
    privileged: true
    ports:
      - "5011:80"
    volumes:
      - /Users/maximilianreihn/Documents/repos/zwift-python-noteboook/zwo_files/:/src/zwo_files/
      #- /volume1/repos/zwift/zwo_files/:/src/zwo_files/